# Generated by Django 4.1.5 on 2023-02-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='default', max_length=400, verbose_name='Описание статьи'),
            preserve_default=False,
        ),
    ]
