# Generated by Django 4.1.5 on 2023-02-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(default=None, max_length=250, verbose_name='Описание статьи'),
        ),
    ]
