# Generated by Django 4.1.5 on 2023-02-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на изображение'),
        ),
    ]
