# Generated by Django 4.1.5 on 2023-02-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_article_article_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_image_url',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Описание категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ключи'),
        ),
    ]
