# Generated by Django 4.1.5 on 2023-02-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_remove_article_article_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ключи'),
        ),
    ]
