# Generated by Django 4.1.5 on 2023-06-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_article_is_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_enabled',
            new_name='is_published',
        ),
    ]
