# Generated by Django 4.1.5 on 2023-07-02 08:56

import articles.fields
import articles.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_alter_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=articles.fields.WEBPField(upload_to=articles.models.image_folder, verbose_name='Image'),
        ),
    ]
